# -*- coding: utf-8 -*-
"""Maternal_ml_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17RQBSBP5lsjLbTA3udD0DdfsUFA2Vu_N
"""

!pip install scikit-learn joblib

import pandas as pd

# Load dataset
df = pd.read_csv("/maternal_risk.csv")

print("First 5 rows:")
display(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns)

# Save original shape
print("Original shape:", df.shape)

# Remove unrealistic maternal ages
df = df[(df['Age'] >= 15) & (df['Age'] <= 50)]

# Remove extreme heart rate values
df = df[(df['HeartRate'] >= 40) & (df['HeartRate'] <= 200)]

# Remove unrealistic body temperature
df = df[(df['BodyTemp'] >= 35) & (df['BodyTemp'] <= 42)]

print("After cleaning shape:", df.shape)

print(df['BodyTemp'].describe())

df = pd.read_csv("maternal_risk.csv")
print("Reloaded shape:", df.shape)

print("Original shape:", df.shape)

df = df[(df['Age'] >= 15) & (df['Age'] <= 50)]
df = df[(df['HeartRate'] >= 40) & (df['HeartRate'] <= 200)]
df = df[(df['BodyTemp'] >= 95) & (df['BodyTemp'] <= 105)]

print("After cleaning shape:", df.shape)

print(df['BodyTemp'].describe())

print("Original shape:", df.shape)

# Age range for pregnancy
df = df[(df['Age'] >= 15) & (df['Age'] <= 50)]

# Heart rate physiological range
df = df[(df['HeartRate'] >= 40) & (df['HeartRate'] <= 200)]

# Body temperature in Fahrenheit
df = df[(df['BodyTemp'] >= 95) & (df['BodyTemp'] <= 105)]

print("After cleaning shape:", df.shape)

df['RiskLevel'] = df['RiskLevel'].map({
    'low risk': 0,
    'mid risk': 1,
    'high risk': 2
})

print("Unique encoded values:")
print(df['RiskLevel'].unique())

from sklearn.model_selection import train_test_split

# Features
X = df[['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate']]

# Target
y = df['RiskLevel']

# Split (stratify keeps class balance)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

print("Training done.")

from sklearn.metrics import classification_report, confusion_matrix

# Predictions
y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print(feature_importance)

import joblib

joblib.dump(model, "maternal_risk_model.pkl")

print("Model saved successfully.")



"""**Life-Link Donor Network**"""

import pandas as pd

donors = pd.DataFrame({
    "Name": ["Asha", "Rahul", "Priya", "Kiran", "Meena", "Arjun", "Divya", "Ravi"],
    "BloodGroup": ["O-", "A+", "B+", "AB+", "O+", "A-", "B-", "O-"],
    "Age": [22, 25, 30, 28, 35, 40, 27, 24],
    "Hemoglobin": [13.5, 11.8, 14.2, 12.9, 13.0, 15.1, 10.5, 14.0],
    "Status": ["Available", "Available", "Unavailable", "Available", "Available", "Available", "Available", "Available"]
})

donors

compatibility = {
    "O-": ["O-"],
    "O+": ["O+", "O-"],
    "A+": ["A+", "A-", "O+", "O-"],
    "A-": ["A-", "O-"],
    "B+": ["B+", "B-", "O+", "O-"],
    "B-": ["B-", "O-"],
    "AB+": ["O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+"],
    "AB-": ["A-", "B-", "AB-", "O-"]
}

def find_donors(patient_blood_group):

    compatible_groups = compatibility[patient_blood_group]

    matched = donors[
        (donors["BloodGroup"].isin(compatible_groups)) &
        (donors["Hemoglobin"] > 12.5) &
        (donors["Age"] >= 18) &
        (donors["Age"] <= 50) &
        (donors["Status"] == "Available")
    ]

    return matched

find_donors("A+")

def emergency_protocol(predicted_risk, patient_blood_group):

    if predicted_risk == 2:  # High Risk
        print("🚨 HIGH RISK DETECTED - Hemorrhage Alert Activated")
        print("Searching for compatible donors...\n")

        matches = find_donors(patient_blood_group)

        if len(matches) > 0:
            return matches
        else:
            print("No eligible donors found.")
            return None
    else:
        print("Patient not in high-risk category. Monitoring recommended.")
        return None

emergency_protocol(2, "A+")





!pip install streamlit pyngrok

streamlit run app.py

